name: CI Security and Testing

on: [push]

jobs:
  # --- СТАДИЯ LINT ---
  bash_lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bash Lint
        run: shellcheck deploy.sh

  yaml_lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run YAML Lint
        run: yamllint .

  # --- СТАДИЯ TEST ---
  python_unit_test:
    runs-on: [self-hosted, Linux, X64]
    needs: [bash_lint, yaml_lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python Unit Tests
        run: pytest-3 test_app.py
