name: CI/CD Pipeline - Security, Testing, Build and Deploy

on: [push]

jobs:
  # --- СТАДИЯ LINT ---
  bash_lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Bash Lint
        run: shellcheck deploy.sh

  yaml_lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run YAML Lint
        run: yamllint .

  # --- СТАДИЯ TEST ---
  python_unit_test:
    runs-on: [self-hosted, Linux, X64]
    needs: [bash_lint, yaml_lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Python Unit Tests
        run: pytest-3 test_app.py

  # --- СТАДИЯ BUILD ---
  docker_build:
    runs-on: [self-hosted, build]
    needs: python_unit_test
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            docker login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/avice66/cicd-demo:latest \
            -t ghcr.io/avice66/cicd-demo:${{ github.run_number }} .

      - name: Push Docker Image to Registry
        run: |
          docker push ghcr.io/avice66/cicd-demo:latest
          docker push ghcr.io/avice66/cicd-demo:${{ github.run_number }}

  # --- СТАДИЯ DEPLOY ---
  deploy_to_test:
    runs-on: [self-hosted, Linux, X64]
    needs: docker_build
    steps:
      - name: Deploy Application via SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ vars.TARGET_HOST }}
          USER: ${{ vars.TARGET_USER }}
          REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_USER: ${{ github.actor }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

          ssh -i ~/.ssh/id_rsa $USER@$HOST "
            echo '$REGISTRY_TOKEN' | \
              docker login ghcr.io \
              -u '$REGISTRY_USER' \
              --password-stdin && \
            docker stop my-python-app || true && \
            docker rm my-python-app || true && \
            docker pull ghcr.io/avice66/cicd-demo:latest && \
            docker run -d \
              --name my-python-app \
              -p 80:3010 \
              ghcr.io/avice66/cicd-demo:latest
          "
          rm -f ~/.ssh/id_rsa
